server:
  port: 8080

spring:
  application:
    name: Togetherly

  datasource:
    url: jdbc:mysql://localhost:3306/togetherly
    username: root
    password: Ramp$0192
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ramp051346@gmail.com
    password: tzox tjvl vphb iijh
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  app:
    frontend:
      base-url: http://localhost:8080
