server:
  port: 8080

spring:
  application:
    name: Togetherly

  security:
    user:
      name: admin
      password: Admin@123

  datasource:
    url: jdbc:mysql://localhost:3306/togetherly
    username: root
    password: Ramp$0192
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
